all : 
	cd dumpdb ; make
	cd todb ; make
	cd getdb ; make

strip :
	cd dumpdb ; make strip
	cd todb ; make strip
	cd getdb ; make strip

clean :
	cd dumpdb ; make clean
	cd todb ; make clean
	cd getdb ; make clean
